### PR TITLE
add tutorial docs on forked branch

### PR DESCRIPTION
**Pull request by hlillemark**

### CODE REVIEW

**Comment by hlillemark** [comment]
Added .rst file made from ECoG_preprocessing_tutorial.ipynb notebook tutorial so that it appears on the read the docs website for process_nwb

**Comment by JesseLivezey** [comment]
I think this should be added as a sphinx gallery
https://sphinx-gallery.github.io/stable/index.html

We have 2 examples using this in this repo
https://github.com/BouchardLab/pyuoi

I'm coming back to work part-time next week, so maybe I can go over the gallery with you and @jthermiz sometime.

**Comment by JesseLivezey** [comment]
Important files/lines for generating gallery

https://github.com/BouchardLab/pyuoi/blob/master/docs/source/index.rst
https://github.com/BouchardLab/pyuoi/tree/master/examples
https://github.com/BouchardLab/pyuoi/blob/4f6f924e52868ac416c8c7848980375a0434d8b0/docs/source/conf.py#L62
https://github.com/BouchardLab/pyuoi/blob/4f6f924e52868ac416c8c7848980375a0434d8b0/docs/source/conf.py#L65

**Comment by JesseLivezey** [comment]
@hlillemark I setup an empty sphinx gallery in the repo. If you add your tutorial as a .py file to the examples folder, it will be added. You'll need to format it according to the sphinx gallery format
https://sphinx-gallery.github.io/stable/syntax.html

You can see 2 example python files here
https://github.com/BouchardLab/pyuoi/tree/master/examples

It's probably easiest to make a new PR with just the single .py file.

**Comment by hlillemark** [comment]
Made new PR with updated changes

**Pull request closed without merging**
