### PR TITLE
Filter options

### LINKED ISSUE #4: How to select bands for wavelet transform?
Figure out what a good standard is for determining bandpass wavelet transform parameters.

### LINKED ISSUE #13: Add ability to just calculate and save HG.

### PR DESCRIPTION
**Pull request by JesseLivezey**
Make center frequency, Q, and frequnecy range selection simpler.

Now `filters` defines the base set of center frequencies and Q.
- `rat` is 2-1200 Hz, 54 bands, constant Q
- `human` is 4-200 Hz, 40 bands, constant Q
- `changlab` is 4-200 Hz, 40 bands, variable Q

 `hg_only` restricts center frequencies to HG range.

Closes #13 
Closes #4

### CODE REVIEW

**Comment by JesseLivezey** [comment]
@emilyps14 @bendichter FYI, this PR will change (and hopefully improve) some of the functionality around choosing what bands to use for the wavelet (hilbert) transform. It will break old code.

**Comment by emilyps14** [comment]
Thanks for the heads up, Jesse. 

@bendichter do you have a plan for updating `ecogvis` or do you need someone on our side to do it?

> @emilyps14 @bendichter FYI, this PR will change (and hopefully improve) some of the functionality around choosing what bands to use for the wavelet (hilbert) transform. It will break old code.

**Comment by emilyps14** [comment]
@JesseLivezey Going forward, would it be possible to have version tags that we can use in our requirements so we can take our time to update our repos?

**Comment by bendichter** [comment]
I wasn't planning on updating ecogVIS. I suppose we could, if there are features that we'd want from recent development. I agree that it would be ideal for this repo to use version numbers so that we can lock to an earlier version and update when ready.

**Comment by JesseLivezey** [comment]
@bendichter @emilyps14 
when I get around to updating the pip version, I'll update the version number. Currently the (only) pip version is 0.1.0 if you want to pin to that.

**Comment by JesseLivezey** [comment]
The only other changes on the horizon are flags to compute/write things like the CAR or wavelet amplitude in an iterative way across time, channels, etc. which we will need for some large rat recordings. They shouldn't break the interface.

**Comment by JesseLivezey** [comment]
And if there's a commit that you've been using between the current pip version and the current github version that would be useful for you, I can make a pip release for that commit as well.

**Pull request merged**
